services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    expose:
      - "8080"
    volumes:
      - ./config:/etc/searxng:rw
    environment:
      - BASE_URL=http://localhost:8080/
    restart: unless-stopped
    networks:
      - searxnet
  url2md:
    build: ./url2md
    container_name: url2md
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - searxnet

networks:
  searxnet:
